# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(max_length=32, upload_to='static/images', verbose_name='图片路径')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('summary', models.CharField(max_length=32, verbose_name='简洁')),
            ],
            options={
                'verbose_name_plural': '图片',
            },
        ),
    ]
